### ISSUE TITLE
Need more explicit error message in case of non-existent provider

### ISSUE THREAD

**Issue by jsztuka** [jenkinsci/jms-messaging-plugin#211]
Hi,
I've recently run into issue during JobDSL smoke tests.
The error message was following:

```
com.redhat.cvp.jobdsl.JobScriptsSpec > test DSL script ci_operator_test_playbooks.groovy STANDARD_ERROR
      51.218 [id=17]    INFO    j.j.plugin.JenkinsJobManagement#createOrUpdateConfig: createOrUpdateConfig for test-operator-test-playbooks
      51.227 [id=17]    INFO    c.r.j.plugins.ci.CIBuildTrigger#stop: job is null! Not stopping trigger thread!
      51.229 [id=17]    SEVERE  c.r.j.plugins.ci.CIBuildTrigger#startTriggerThreads: Unhandled exception in trigger start.
    java.lang.NullPointerException
        at com.redhat.jenkins.plugins.ci.threads.CITriggerThread.<init>(CITriggerThread.java:53)
        at com.redhat.jenkins.plugins.ci.CIBuildTrigger.getComparisonThreads(CIBuildTrigger.java:367)
        at com.redhat.jenkins.plugins.ci.CIBuildTrigger.stopTriggerThreads(CIBuildTrigger.java:317)
        at com.redhat.jenkins.plugins.ci.CIBuildTrigger.startTriggerThreads(CIBuildTrigger.java:293)
        at com.redhat.jenkins.plugins.ci.CIBuildTrigger.start(CIBuildTrigger.java:253)
        at com.redhat.jenkins.plugins.ci.CIBuildTrigger.start(CIBuildTrigger.java:83)
        at org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty.startTriggers(PipelineTriggersJobProperty.java:113)
        at org.jenkinsci.plugins.workflow.job.WorkflowJob.addProperty(WorkflowJob.java:201)
        at org.jenkinsci.plugins.workflow.job.WorkflowJob.setTriggers(WorkflowJob.java:469)
        at org.jenkinsci.plugins.workflow.job.WorkflowJob.onLoad(WorkflowJob.java:145)
        at hudson.model.Items.load(Items.java:373)
```
I was using rabbitMQSubscriber in my job specification groovy file.
This error ment that I was just referencing to provider which was absent in my jenkins global configuration.
I propose changing this error msg to something more explicit so user realises he/she referred to a non-existent provider.

Thanks in advance.

**Comment by ggallen** [comment]
This is fixed in the latest code.  Take this code:
```
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                sendCIMessage activeMQPublisher(messageContent: '{ "msg": "content"}', messageProperties: 'foo=bar', name: 'AMQ1')
            }
        }
    }
}

```
It results in this error:
```
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 89c6c442-49db-4f89-a3a9-5d8d9e1cb056
java.lang.Exception: Unrecognized provider name: AMQ1
	at PluginClassLoader for jms-messaging//com.redhat.jenkins.plugins.ci.pipeline.CIMessageSenderStep$Execution.start(CIMessageSenderStep.java:103)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:323)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:180)
	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at PluginClassLoader for script-
```
