### ISSUE TITLE
RabbitMQMessagingWorker can't subscribe to jenkins job

### ISSUE THREAD

**Issue by jsztuka** [jenkinsci/jms-messaging-plugin#213]
`2021-01-11 10:57:32.588+0000 [id=124198]	INFO	c.r.j.p.c.m.RabbitMQMessagingWorker#subscribe: Subscribing job 'cvp-co-metadata-trigger' to org.fedoraproject.prod.github.issue.comment topic.
2021-01-11 10:57:32.589+0000 [id=124198]	SEVERE	c.r.j.p.c.m.RabbitMQMessagingWorker#subscribe: Eexception raised while subscribing job 'cvp-co-metadata-trigger', retrying in 1 minutes.
java.lang.NullPointerException
	at com.redhat.jenkins.plugins.ci.messaging.RabbitMQMessagingWorker.subscribe(RabbitMQMessagingWorker.java:74)
	at com.redhat.jenkins.plugins.ci.messaging.JMSMessagingWorker.subscribe(JMSMessagingWorker.java:49)
	at com.redhat.jenkins.plugins.ci.messaging.RabbitMQMessagingWorker.receive(RabbitMQMessagingWorker.java:158)
	at com.redhat.jenkins.plugins.ci.threads.CITriggerThread.run(CITriggerThread.java:73)
2021-01-11 10:57:32.589+0000 [id=124198]	WARNING	c.r.j.p.c.m.RabbitMQMessagingWorker#unsubscribe: Exception occurred when closing channel: null`

This makes the job cvp-co-metadata-trigger non-functional (won't trigger new builds).

**Comment by jsztuka** [comment]
The possible solution is created here:
https://github.com/jenkinsci/jms-messaging-plugin/pull/212

**Comment by ggallen** [comment]
This appears to be fixed by #212.
