### ISSUE TITLE
Failover broker URL does not failover subscribed jobs when one of the brokers is no longer available

### ISSUE THREAD

**Issue by pholica** [jenkinsci/jms-messaging-plugin#237]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>
Jenkins: 2.303.3
OS: Linux - redacted
---
(redacted other plugins due to security concerns)
jms-messaging:1.1.26
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

RHEL-7

### Reproduction steps

1. Configure brokers using failover url like: failover:(ssl://01.example.com:61616,ssl://02.example.com:61616)
2. Create a job that is triggered by CI message
3. Check which broker was used for subscription
4. Make the broker inaccessible (e.g. using iptables)

### Expected Results

Job is re-subscribed using the other broker configured in the failover URL

### Actual Results

The plugin tries resubscribing again and again using the broker that was used for the initial subscribe:
Following messages are available in log:
```
2022-05-29 03:56:55.543+0000 [id=312088]        WARNING o.a.a.t.f.FailoverTransport#doReconnect: Failed to connect to [ssl://01.example.com:61616] after: 4780 attempt(s) with Connection refused (Connection refused), continuing to retry.
```

### Anything else?

I'm not sure if it's somehow related, but the first issue we hit with the broker before it went fully offline (refusing connections) was:
```
2022-05-23 18:45:02.019+0000 [id=3095047]       WARNING o.a.a.t.f.FailoverTransport#handleTransportFailure: Transport (ssl://01.example.com:61616) failed, attempting to automatically reconnect
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:268)
        at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240)
        at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232)
        at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ggallen** [comment]
I set my broker URL as follows:
```
failover:(tcp://primary:61616,tcp://backup:61616,tcp://localhost:61616)
```
The last one is the only valid one.  I then disabled and enabled my job so the trigger thread would restart.  I get this output:
```
2025-06-10 22:18:35.719+0000 [id=148]	INFO	c.r.j.plugins.ci.CIBuildTrigger#startTriggerThreads: Starting thread (312) for 'squash'.
2025-06-10 22:18:35.720+0000 [id=312]	SEVERE	o.a.a.t.f.FailoverTransport#compareURIs: Failed to Lookup INetAddress for URI[tcp://backup:61616]
2025-06-10 22:18:35.720+0000 [id=312]	SEVERE	o.a.a.t.f.FailoverTransport#compareURIs: Failed to Lookup INetAddress for URI[tcp://primary:61616]
2025-06-10 22:18:35.720+0000 [id=312]	SEVERE	o.a.a.t.f.FailoverTransport#compareURIs: Failed to Lookup INetAddress for URI[tcp://backup:61616]
2025-06-10 22:18:35.723+0000 [id=313]	INFO	o.a.a.t.f.FailoverTransport#doReconnect: Successfully connected to tcp://localhost:61616
```
It tries the first two before succeeding on connecting to the last one.

**Comment by ggallen** [comment]
I started two containers on my laptop, port-forwarding 61616:61616 and 61617:61616 to each.  I then configured an AMQ provider with this as the broker URL:
```
failover:(tcp://localhost:61616,tcp://localhost:61617)
```
I then configured a job to use the AMQ provider. It connected without issue to 61617. Then I shut down the container listening on the 61617 port and checked the Jenkins log.  It got disconnected from 61617 and then reconnected using 61616 as expected. Here's the output:
```
2025-06-11 14:16:35.223+0000 [id=51]	INFO	jenkins.model.Jenkins#setInstallState: Install state transitioning from: null to: DEVELOPMENT
2025-06-11 14:16:35.360+0000 [id=101]	INFO	o.a.a.t.f.FailoverTransport#doReconnect: Successfully connected to tcp://localhost:61617
2025-06-11 14:16:35.371+0000 [id=96]	INFO	c.r.j.p.c.m.ActiveMqMessagingWorker#connect: Connection started
2025-06-11 14:16:35.371+0000 [id=96]	INFO	c.r.j.p.c.m.ActiveMqMessagingWorker#subscribe: Subscribing job 'squash' to 'VirtualTopic.qe.ci.>' topic.
2025-06-11 14:16:35.393+0000 [id=96]	INFO	c.r.j.p.c.m.ActiveMqMessagingWorker#subscribe: Successfully subscribed job 'squash' to 'VirtualTopic.qe.ci.>' topic with selector: null
2025-06-11 14:16:35.393+0000 [id=96]	INFO	c.r.j.p.c.m.ActiveMqMessagingWorker#receive: Job 'squash' waiting to receive message
2025-06-11 14:16:35.406+0000 [id=83]	INFO	java_util_logging_Logger$info$0#call: Setup AMQ Messaging Provider
2025-06-11 14:16:35.427+0000 [id=83]	WARNING	java_util_logging_Logger$warning$1#call: Attempt to add a duplicate message provider
2025-06-11 14:16:35.427+0000 [id=83]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /home/gallen/work/kubearchive/jms-messaging-plugin/plugin/work/init.groovy.d/disable-csrf.groovy
2025-06-11 14:16:35.456+0000 [id=83]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2025-06-11 14:16:35.482+0000 [id=39]	INFO	hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
2025-06-11 14:17:18.155+0000 [id=103]	WARNING	o.a.a.t.f.FailoverTransport#handleTransportFailure: Transport (tcp://localhost:61617) failed, attempting to automatically reconnect
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:386)
	at PluginClassLoader for jms-messaging//org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:280)
	at PluginClassLoader for jms-messaging//org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240)
	at PluginClassLoader for jms-messaging//org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232)
	at PluginClassLoader for jms-messaging//org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
	at java.base/java.lang.Thread.run(Thread.java:840)
2025-06-11 14:17:18.170+0000 [id=123]	INFO	o.a.a.t.f.FailoverTransport#doReconnect: Successfully reconnected to tcp://localhost:61616
```
So I can't seem to reproduce this problem.
