### ISSUE TITLE
jms-messaging-plugin fails to resubscribe to a topic

### ISSUE THREAD

**Issue by thrix** [jenkinsci/jms-messaging-plugin#244]
### Jenkins and plugins versions report

From time to time our Jenkins fails to resubscribe to our AMPQ queue (UMB). We added monitoring for the logs and need to disable/enable job to force resubscription.

Happens with 1.1.26 and 1.1.27 plugin versions.

````
2022-07-27 14:24:27.079+0000 [id=65]	INFO	c.r.j.p.c.m.ActiveMqMessagingWorker#unsubscribe: Unsubscribing job 'ci-brew-dispatcher' from the 'Consumer.msg-client-citool.5086ca03-39dd-5fcb-8e6d-e346b016c773.VirtualTopic.eng.brew.task.closed.>' topic.
2022-07-27 14:24:27.108+0000 [id=65]	SEVERE	c.r.j.p.c.t.CITriggerThread#run: Thread CIBuildTrigger-ci-brew-dispatcher-1-ActiveMqMessagingProvider completed
2022-07-27 14:24:27.110+0000 [id=65]	SEVERE	h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (CIBuildTrigger-ci-brew-dispatcher-1-ActiveMqMessagingProvider/65) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.StackOverflowError
	at org.acegisecurity.context.SecurityContext$1.getAuthentication(SecurityContext.java:46)
	at org.acegisecurity.context.SecurityContext$2.getAuthentication(SecurityContext.java:60)
	at org.acegisecurity.context.SecurityContext$1.getAuthentication(SecurityContext.java:46)
	at org.acegisecurity.context.SecurityContext$2.getAuthentication(SecurityContext.java:60)
[snip]
````

### What Operating System are you using (both controller, and any agents involved in the problem)?

````
Jenkins: 2.303.3
OS: Linux - 3.10.0-1062.4.3.el7.x86_64
jms-messaging:1.1.27
````

### Reproduction steps

Subscribe to a AMQP queue, watch the jenkins log

### Expected Results

Plugin resubscribes flawlessly

### Actual Results

Occasionally, the plugin fails to resubscribe to a queue and tracebacks

**Comment by thrix** [comment]
@olivergondza any ideas here? We see this randomly, but fairly often with our Jenkins instances

**Comment by ggallen** [comment]
Did you get this reversed with "Expected Results"?

> ### Actual Results
>
> Plugin resubscribes flawlessly

**Comment by thrix** [comment]
@ggallen of course, fixed :)

**Comment by guy9050** [comment]
I encounter the same issue as well.

**Comment by thrix** [comment]
@ggallen @olivergondza, do we need to provide further information here? This happens to us regularly.

**Comment by thrix** [comment]
still happening

**Comment by ggallen** [comment]
I'm assuming this is fixed as described in the previous comment.

If it happens again, please open a new issue.
